### ISSUE TITLE
Firebase Realtime Database: Size limit on writes

### ISSUE THREAD

**Issue by Matthias-Schaub** [mapswipe/python-mapswipe-workers#143] opened 2019-08-30 07:51 UTC
Firebase Realtime Database has limit on writes.
Size of a single write request to the database: 256 MB from the REST API; 16 MB from the SDKs
https://firebase.google.com/docs/database/usage/limits#writes

Upload of the `task` json object to the Firebase by the back-end can surpass this limit. 

Use sys.getsizeof(object[, default]) to determine if limit is surpassed:
https://docs.python.org/3/library/sys.html#sys.getsizeof

**Comment by Hagellach37** [comment] 2019-08-30 09:12
duplicate of #142

**Closed by Hagellach37** 2019-08-30 09:12 UTC
